-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIITUt4soPBSmi0HFvZcGjGrskM+3Stz2GcfbZVxALX/SoAoGCCqGSM49
AwEHoUQDQgAESIBhhDamsacy/6zWYBI6soPmCDEsEFsWARHCei4BmeGsn/v3vMve
F6YgNUfAw7GXtPsc/K8ubQ42sutcBia5Mw==
-----END EC PRIVATE KEY-----
