FROM docker.io/library/alpine:3.16.0
FROM docker.io/library/eclipse-temurin:17.0.3_7-jre-alpine

ENV PATH="/certusine/bin:${PATH}"
ENV _JAVA_OPTIONS "-Djava.awt.headless=true"

COPY certusine /certusine

LABEL "org.opencontainers.image.authors"="Mark Raynsford"
LABEL "org.opencontainers.image.description"="The Certusine ACME client."
LABEL "org.opencontainers.image.licenses"="ISC"
LABEL "org.opencontainers.image.source"="https://www.github.com/io7m/certusine"
LABEL "org.opencontainers.image.title"="Certusine"
LABEL "org.opencontainers.image.url"="https://www.io7m.com/software/certusine"
LABEL "org.opencontainers.image.version"="0.0.1"

VOLUME "/certusine/etc"

CMD ["/certusine/bin/certusine"]
