{
 "title": "Certusine",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Metrics", "query": "prometheus" },
   { "name": "instance", "query": { "query": "label_values(certusine_up,job)" } },
   { "name": "Traces", "query": "tempo" },
   { "name": "Logs", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(certusine_certificates_store_failures_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Store"
    },
    {
     "expr": "rate(certusine_dns_challenge_failures_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "DNS Challenge"
    },
    {
     "expr": "rate(certusine_signing_failures_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Signing"
    }
   ]
  },
  {
   "title": "Renewals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(certusine_renewal_successes_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Successes"
    },
    {
     "expr": "rate(certusine_renewal_failures_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "timeseries",
   "description": "Internal task executions.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(certusine_tasks_executed_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Executed"
    },
    {
     "expr": "rate(certusine_tasks_succeeded_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "rate(certusine_tasks_failed_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Failed"
    },
    {
     "expr": "rate(certusine_tasks_retried_total{job=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Retried"
    }
   ]
  },
  {
   "title": "Certificate Validity Remaining",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "certusine_certificate_time_remaining{job=~\"$instance\"}",
     "legendFormat": "{{certificate}}.{{domain}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"$instance\"} | json",
     "maxLines": 100
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    { "limit": 20, "serviceName": "certusine" }
   ]
  }
 ]
}